def parse_line_less_1998(line):
    mundef = line[:3].strip()
    provdef = line[3:5].strip()
    mesna = line[5:7].strip()
    anona = '1' + line[7:10].strip()
    sexo = line[10].strip()
    eciv = line[11].strip()
    profe = line[12:14].strip()
    munires = line[14:17].strip()
    provres = line[17:19].strip()
    mesdef = line[19:21].strip()
    anodef = '19' + line[21:23].strip()
    anoscum = line[27:30].strip()
    mescum = line[30:32].strip() # Si menores de 1 anio
    diascum = line[32:34].strip() # Si menores de 1 mes
    tamamuni = line[34].strip()
    tamamunr = line[35].strip()
    return [provdef,mundef,mesna,anona,sexo,mesdef,anodef,"","","","","","","",provres,munires,"",eciv,profe,anoscum,mescum,diascum,tamamuni,"",tamamunr,"","","","","","","","","",""]

def parse_line_less_2008(line):
    mundef = line[:3].strip()
    provdef = line[3:5].strip()
    mesna = line[5:7].strip()
    anona = line[7:11].strip()
    provnac = line[11:13].strip()
    sexo = line[13].strip()
    eciv = line[14].strip()
    nacion = line[15:18].strip()
    profe = line[18:20].strip()
    munires = line[20:23].strip()
    provres = line[23:25].strip()
    mesdef = line[25:27].strip()
    anodef = line[27:31].strip()
    anoscum = line[35:38].strip()
    mescum = line[38:40].strip() # Si menores de 1 anio
    diascum = line[40:42].strip() # Si menores de 1 mes
    tamamuni = line[42].strip()
    tamamunr = line[43].strip()
    munnac = line[51:54].strip()
    return [provdef,mundef,mesna,anona,sexo,mesdef,anodef,nacion,"","",provnac,munnac,"","",provres,munires,"",eciv,profe,anoscum,mescum,diascum,tamamuni,"",tamamunr,"","","","","","","","","",""]

def parse_line_less_2015(line):
    provdef = line[:2].strip()
    mundef = line[2:5].strip()
    mesna = line[5:7].strip()
    anona = line[7:11].strip()
    sexo = line[11].strip()
    mesdef = line[12:14].strip()
    anodef = line[14:18].strip()
    nacion = line[18].strip()
    paisnac = line[19:22].strip()
    lugnac = line[22].strip()
    provnac = line[23:25].strip()
    munnac = line[25:28].strip()
    paisnacex = line[28:31].strip()
    lugres = line[31].strip()
    provres = line[32:34].strip()
    munires = line[34:37].strip()
    paisresex = line[37:40].strip()
    eciv = line[40].strip()
    profe = line[41:43].strip()
    anoscum = line[43:46].strip()
    mescum = line[46:48].strip()
    diascum = line[48:50].strip()
    tamamuni = line[50].strip()
    tamamunn = line[51].strip()
    tamamunr = line[52].strip()
    tamapaisnac = line[53].strip()
    tamapaisres = line[54].strip()
    tamapaisnacion = line[55].strip()
    cmbas = line[56:60].strip()
    cmred = line[60:63].strip()
    cmper = line[63:65].strip()
    cminf = line[65:67].strip()
    return [provdef,mundef,mesna,anona,sexo,mesdef,anodef,nacion,paisnac,lugnac,provnac,munnac,paisnacex,lugres,provres,munires,paisresex,eciv,profe,anoscum,mescum,diascum,tamamuni,tamamunn,tamamunr,tamapaisnac,tamapaisres,tamapaisnacion,cmbas,cmred,cmper,cminf,"","",""]    

def parse_line_less_2019(line):
    provdef = line[:2].strip()
    mundef = line[2:5].strip()
    mesna = line[5:7].strip()
    anona = line[7:11].strip()
    sexo = line[11].strip()
    mesdef = line[12:14].strip()
    anodef = line[14:18].strip()
    nacion = line[18].strip()
    paisnac = line[19:22].strip()
    lugnac = line[22].strip()
    provnac = line[23:25].strip()
    munnac = line[25:28].strip()
    paisnacex = line[28:31].strip()
    lugres = line[31].strip()
    provres = line[32:34].strip()
    munires = line[34:37].strip()
    paisresex = line[37:40].strip()
    eciv = line[40].strip()
    profe = line[41:43].strip()
    anoscum = line[43:46].strip()
    mescum = line[46:48].strip()
    diascum = line[48:50].strip()
    tamamuni = line[50].strip()
    tamamunn = line[51].strip()
    tamamunr = line[52].strip()
    tamapaisnac = line[53].strip()
    tamapaisres = line[54].strip()
    tamapaisnacion = line[55].strip()
    cmbas = line[56:60].strip()
    cmred = line[60:63].strip()
    cmper = line[63:65].strip()
    cminf = line[65:67].strip()
    nedu = line[67:69].strip()
    lugdef = line[69].strip()
    rela = line[70].strip()

    return [provdef,mundef,mesna,anona,sexo,mesdef,anodef,nacion,paisnac,lugnac,provnac,munnac,paisnacex,lugres,provres,munires,paisresex,eciv,profe,anoscum,mescum,diascum,tamamuni,tamamunn,tamamunr,tamapaisnac,tamapaisres,tamapaisnacion,cmbas,cmred,cmper,cminf,nedu,lugdef,rela]