def parse_line_less_1998(line):
    mundef = line[:3]
    provdef = line[3:5]
    mesna = line[5:7]
    anona = '1' + line[7:10]
    sexo = line[10]
    eciv = line[11]
    profe = line[12:14]
    munires = line[14:17]
    provres = line[17:19]
    mesdef = line[19:21]
    anodef = '19' + line[21:23]
    anoscum = line[27:30]
    mescum = line[30:32] # Si menores de 1 anio
    diascum = line[32:34] # Si menores de 1 mes
    tamamuni = line[34]
    tamamunr = line[35]
    return [provdef,mundef,mesna,anona,sexo,mesdef,anodef,"","","","","","","",provres,munires,"",eciv,profe,anoscum,mescum,diascum,tamamuni,"",tamamunr,"","","","","","","","","",""]

def parse_line_less_2008(line):
    mundef = line[:3]
    provdef = line[3:5]
    mesna = line[5:7]
    anona = line[7:11]
    provnac = line[11:13]
    sexo = line[13]
    eciv = line[14]
    nacion = line[15:18]
    profe = line[18:20]
    munires = line[20:23]
    provres = line[23:25]
    mesdef = line[25:27]
    anodef = line[27:31]
    anoscum = line[35:38]
    mescum = line[38:40] # Si menores de 1 anio
    diascum = line[40:42] # Si menores de 1 mes
    tamamuni = line[42]
    tamamunr = line[43]
    munnac = line[51:54]
    return [provdef,mundef,mesna,anona,sexo,mesdef,anodef,nacion,"","",provnac,munnac,"","",provres,munires,"",eciv,profe,anoscum,mescum,diascum,tamamuni,"",tamamunr,"","","","","","","","","",""]

def parse_line_less_2015(line):
    provdef = line[:2]
    mundef = line[2:5]
    mesna = line[5:7]
    anona = line[7:11]
    sexo = line[11]
    mesdef = line[12:14]
    anodef = line[14:18]
    nacion = line[18]
    paisnac = line[19:22]
    lugnac = line[22]
    provnac = line[23:25]
    munnac = line[25:28]
    paisnacex = line[28:31]
    lugres = line[31]
    provres = line[32:34]
    munires = line[34:37]
    paisresex = line[37:40]
    eciv = line[40]
    profe = line[41:43]
    anoscum = line[43:46]
    mescum = line[46:48]
    diascum = line[48:50]
    tamamuni = line[50]
    tamamunn = line[51]
    tamamunr = line[52]
    tamapaisnac = line[53]
    tamapaisres = line[54]
    tamapaisnacion = line[55]
    cmbas = line[56:60]
    cmred = line[60:63]
    cmper = line[63:65]
    cminf = line[65:67]
    return [provdef,mundef,mesna,anona,sexo,mesdef,anodef,nacion,paisnac,lugnac,provnac,munnac,paisnacex,lugres,provres,munires,paisresex,eciv,profe,anoscum,mescum,diascum,tamamuni,tamamunn,tamamunr,tamapaisnac,tamapaisres,tamapaisnacion,cmbas,cmred,cmper,cminf,"","",""]    

def parse_line_less_2019(line):
    provdef = line[:2]
    mundef = line[2:5]
    mesna = line[5:7]
    anona = line[7:11]
    sexo = line[11]
    mesdef = line[12:14]
    anodef = line[14:18]
    nacion = line[18]
    paisnac = line[19:22]
    lugnac = line[22]
    provnac = line[23:25]
    munnac = line[25:28]
    paisnacex = line[28:31]
    lugres = line[31]
    provres = line[32:34]
    munires = line[34:37]
    paisresex = line[37:40]
    eciv = line[40]
    profe = line[41:43]
    anoscum = line[43:46]
    mescum = line[46:48]
    diascum = line[48:50]
    tamamuni = line[50]
    tamamunn = line[51]
    tamamunr = line[52]
    tamapaisnac = line[53]
    tamapaisres = line[54]
    tamapaisnacion = line[55]
    cmbas = line[56:60]
    cmred = line[60:63]
    cmper = line[63:65]
    cminf = line[65:67]
    nedu = line[67:69]
    lugdef = line[70]
    rela = line[71]

    return [provdef,mundef,mesna,anona,sexo,mesdef,anodef,nacion,paisnac,lugnac,provnac,munnac,paisnacex,lugres,provres,munires,paisresex,eciv,profe,anoscum,mescum,diascum,tamamuni,tamamunn,tamamunr,tamapaisnac,tamapaisres,tamapaisnacion,cmbas,cmred,cmper,cminf,nedu,lugdef,rela]